### ISSUE TITLE
스크롤을 아래로 내렸을 때 최상단으로 바로가는 버튼 생성

### ISSUE THREAD

**Issue by lynn-hong** [dos-tacos/dos-tacos.github.io#13]
## Summary

- 현재는 스크롤을 아래로 내렸을 때 최상단으로 올라가려면 다시 스크롤링을 해야 함

## Todo

- [ ] 최상단으로 바로가는 버튼 생성
- [ ] 기능적으로 문제가 없음
- [ ] 디자인적으로 문제가 없음

## Importance

- 시급성 높음
