### ISSUE TITLE
웹 페이지 layout 변경(공백 축소, 폰트 축소 등)

### ISSUE THREAD

**Issue by lynn-hong** [dos-tacos/dos-tacos.github.io#9]
## Summary

- 현재 좌우에 많이 남는 공백을 줄이고 전체적으로 좀더 예쁘게 보이도록 변경
- 이 때 사이드바의 폰트 사이즈는 변함이 없어야 함

## Todo

- [x] 개별 포스트 화면에서 좌우 공백 축소
- [x] 전체적으로 폰트 사이즈 축소
- [x] nested bullet인 경우에도 지나치게 사이즈가 작아지지 않도록 함

## Importance

- 시급함. 블로그 홍보되기 전에 모든 디자인 작업 끝나야 함

**Comment by lynn-hong** [comment]
- 혹시 폰트 사이즈가 작아지지 않은 경우는 캐시가 남아있기 때문이므로 브라우저를 껐다 켜거나 캐시 삭제 후 재시도

**Comment by lynn-hong** [comment]
document 기본 font-size는 _reset.scss 에서 정의됨
